### ISSUE TITLE
Proporcionar ubicación del modelo multicriterio de vulnerabilidad costera

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/espejos-lancis#1]
@CarlosCruzVz durante la reunión del día 27 de septiembre en Sisal, se generaron tres versiones del modelo multicriterio:

1. modelo_vulnerabilidad_costera_27sep2018_nortes.sdmod
2. modelo_vulnerabilidad_costera_27sep2018_huracanes.sdmod
3. modelo_vulnerabilidad_costera_27sep2018_clima_medio.sdmod

La descripción de los nuevos criterios se encuentran en la minuta:
minuta_3a_reunion_25al18sep2018_papiit.docx

Los archivos se encuentran en el dropbox:
\PAPIIT\pap_talleres\merida\pap_merida25_29sep2018

**Comment by CarlosCruzVz** [comment]
Muchas gracias @edithvilla lo reviso, si tengo dudas te aviso

**Comment by CarlosCruzVz** [comment]
Hola @edithvilla, oye para la parte social, quedaron en mandarnos algunos insumos, podrías pasarme el correo de la chica encargada, saludos

**Comment by edithvilla** [comment]
@CarlosCruzVz los correos de las investigadoras encargadas te los mando por correo electrónico que son las que están en Mérida. @estrada es la que está aquí en CU colaborando con ellas
