### ISSUE TITLE
Realizar propuesta de cuestionario para el modelo socio-institucional #papiit

### ISSUE THREAD

**Issue by aleestrada** [lancis-apc/espejos-lancis#11]
Con base en las variables del modelo realizado por el equipo socio-institucional, se realizará una propuesta de cuestionario, con el objetivo de obtener la información necesaria para el modelo, que no esté disponible en las estadísticas de fuentes formales.

Responsables:
@aleestrada, Bertha e @iaga 

# Insumos
Matriz de Operacionalización de Conceptos: \CARPETAS_TRABAJO\aestrada\papiit\criterios

# Proceso
- [x] Realizar diagramas de árbol en el que se desglosen las capitales analizados en el modelo y los criterios considerados en cada uno de ellos.
- [x] Analizar con Luis los criterios que se consideran en cada uno de los capitales, con el objetivo de optimizar el número de criterios que serán considerados en la elaboración del cuestionario del equipo socio-institucional.
- [x] Generar nuevo diagrama de árbol con las modificaciones realizadas en la reunión con Luis.
- [x] Realizar la propuesta de cuestionario.

**Comment by iaga** [comment]
## Reunión de trabajo con el equipo socio-institucional

Se realizó una reunión (Elena, @aleestrada  e @iaga) el día 17/01/2019 para comunicar al equipo socio-institucional sobre la optimización de criterios realizada. La minuta de la reunión **equipo_social_17ene2019.docx** se encuentra ubicada en la carpeta:

\CARPETAS_TRABAJO\aestrada\papiit\criterios

Como resultado de la reunión, surgieron una serie de preguntas importantes a responder en el cuestionario:

- ¿qué refugios conoce?, ¿A qué refugios acude?
- ¿A qué se dedica?, ¿Qué otras actividades tiene además de ésta?
-  ¿trabajo fuera de la comunidad?
- ¿Pertenece a una cooperativa?
- *¿Pertenece a alguna empresa?* (Consultar con Luis)
- ¿Conoce el protocolo de prevención?
- ¿A dónde acude en caso de desastre?
- ¿Existen organizaciones civiles?
- ¿El hogar participa en la organización civil?
- ¿Se forma parte activa en la red de apoyo?
- ¿Qué obtiene del manglar?



### Acuerdos:
- @aleestrada realizará un análisis del muestreo
- Elena generará un resumen sobre los aspectos relevantes de la información obtenida en las entrevistas

 La próxima reunión será el Martes 22/01/2017 a las 10:00 am y tendrá como objetivo generar la primera propuesta de cuestionario.

**Comment by aleestrada** [comment]
Como resultado de la reunión con Luis es día 16 de enero se optimizaron los criterios del modelo socio-institucional.
El archivo con el modelo original se encuentra en la siguiente liga: 
\CARPETAS_TRABAJO\aestrada\papiit\criterios\variables_socioinsti_merida

El archivo con los criterios optimizados se encuentra en:
\CARPETAS_TRABAJO\aestrada\papiit\criterios\variables_socioinsti_merida_v2

**Comment by aleestrada** [comment]
# Reunión de trabajo del equipo socio-institucional

En la junta de hoy, con Bertha, Ileana, Eliana y Elena, se socializaron los principales hallazgos de las entrevistas realizadas a los actores principales. De igual forma se realizó el primer borrador del cuestionario.

Acuerdos:
- La próxima reunión será el viernes 25/01/2019 a las 11:00 am
- El objetivo de la reunión será revisar las propuestas para la versión final de la encuesta.

**Comment by iaga** [comment]
# Reunión de trabajo del día viernes 25/01/2019
- Se realizó una segundo borrador del cuestionario en la que se incorporaron las observaciones recientes.

## Acuerdos:
- [ ] Alejandra e Ileana incorporarán los acuerdos de la reunión
- [ ] Elena incluirá las preguntas pertinentes
- [ ] Alejandra e Ileana discutirán la primera versión final con Luis
- [ ] La siguiente reunión será el Miércoles para definir la versión que se utilizará en la prueba piloto

**Comment by aleestrada** [comment]
@yosunemiquela

**Comment by aleestrada** [comment]
@salva17ga
