### ISSUE TITLE
Documentar los acuerdos de las reuniones 

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/espejos-lancis#120]
### Exposición

- Documentación técnica
 - Cambiar de ancho de playa a Distancia a la playa

### Resiliencia
- Corregir el sentido de la función de distancia a pastos marinos
- Verificar la capa de Ancho de playa
- Verificar la capa de tipo de litoral, voltear las funciones de valor de los criterios que la componen y llevarlos a ideal 

### Sensibilidad 
 - Verificación de que todo se encuentre bien en la documentación técnica

**Comment by vichdzgeo** [comment]
@yosunemiquela

**Comment by vichdzgeo** [comment]
# 17 febrero 2020

ruta de la información: 
C:\Dropbox (LANCIS)\SIG\desarrollo\sig_papiit\procesamiento\bcs\insumos



Actividades:

- [ ] Revisar las capas entregadas de BCS (tamaño de pixel, proyección, extent) -> carpeta capas

- [ ] Verificar el archivo de excel y localizar las capas  -> archivo capas.xlsx

- [ ]  Recortar las capas a la zona de estudio

- [ ] Integrar las capas en Qgis  con el código de sensibilidad.

- [ ] Crear los proyectos en Qgis de exposición, susceptibilidad y capacidad adaptativa

**Comment by yosunemiquela** [comment]
@vichdzgeo darle seguimiento a las actividades pendientes:
1. Corrección del sentido de la función de distancia a pastos marinos
2. Verificar capa de ancho de playa
3. Verificar capa de tipo de litoral, voltear las funciones de valor y los criterios que la componen
4. Cambiar el nombre del criterio en la gráfica @vichdzgeo @Nayita
