### ISSUE TITLE
Solicitar o adquirir la capa de la zona economica especial  (ZEE) de progreso Yucatán #PAPIIT

### ISSUE THREAD

**Issue by vichdzgeo** [lancis-apc/espejos-lancis#16]
## Carpeta de trabajo

SIG\desarrollo\sig_papiit\procesamiento\zee_progreso

## Insumos
En el documento de la Declaratoria Zona Económica Especial de Progreso - Planos de Polígono de ZEE y Sección Federal, documento descargado
- [/insumos/2017_12_19_MAT_shcp_ZEE_Progreso.pdf](https://www.gob.mx/cms/uploads/attachment/file/309156/2017_12_19_MAT_shcp_ZEE_Progreso.pdf)

## Procesamiento

Del documento se extraen las coordenadas UTM del poligono y se almacenan en un csv.

Archivo: 
- insumos/tp_tp_zee_progreso.csv

Se abre en qgis y se transforma en poligono asociando la proyección de los datos.

## Producto
SIG/desarrollo/sig_papiit/entregables/zee_progreso/zee_progreso.shp

**Comment by CarlosCruzVz** [comment]
@vichdzgeo esta capa corresponde a alguno de los bloques en los que estamos trabajando (biológicos, físicos o sociales) o es una capa independiente?

**Comment by vichdzgeo** [comment]
Es parte de los insumos que en dado momento se ocuparan, por ello es importante tenerla, no obstante, este issue fue creado como una tarea autoasignada, que sirve para ilustrar el procedimiento de como se crea un issue por capa, como se reporta la carpeta de trabajo,insumos, el procesamiento y como se reporta la ruta del producto (capa) esperada, que ya se localiza en entregables. 

Me falta solamente realizar los metadatos de la capa. 

@CarlosCruzVz @ccalderong @Javierroto
