### ISSUE TITLE
Capacitar a los colaboradores en el uso de los protocolos #papiit

### ISSUE THREAD

**Issue by edithvilla** [lancis-apc/espejos-lancis#3]
Revisar los siguientes protocolos @CorinaCantero @gtorres94 @FernandaMN en la página del github:
https://lancis-apc.github.io/planeacion-colaborativa/

Protocolo para el manejo de la información geográfica
Manual para la creación de metadatos geográficos con GeoNetwork
Procedimiento de organización general
Reglamento para el uso de GitHub y Dropbox

En el Manual para la creación de metadatos geográficos con GeoNetwork (https://lancis-apc.github.io/planeacion-colaborativa/manual_geonetwork/manual_metadatos.html)
viene la liga para llenar el formulario de solicitud de cuenta.

Es necesario tener usuario para el seminario de capacitación en la creación de metados geográficos con GeoNetwork

**Comment by gtorres94** [comment]
@vichdzgeo podrías revisar el de Sitios Ramsar por favor.

**Comment by vichdzgeo** [comment]
@gtorres94  ya la revise, muy bien. solo unos comentarios:


- Descarga la información y colócala en la carpeta de dropbox:  ->  \sig_becarios\entregables\ 
- Contesta el formulario de Entregas de capas geográficas - APC

**Comment by edithvilla** [comment]
@CorinaCantero Aguas continentales son: ríos, lagos, lagunas, ojos de agua, cenotes, etc

**Comment by edithvilla** [comment]
@Javierroto @CarlosCruzVz @ccalderong  por favor si pueden mandarme por correo su usuario de skype para el seminario de capacitación del día viernes 7 de diciembre de 11 a 13:30

**Comment by ccalderong** [comment]
Hola, mi nombre de usuario es: caro_calg
________________________________

**Comment by Javierroto** [comment]
Hola

El mio es: javier_roto

Saludos

Javier

**Comment by CarlosCruzVz** [comment]
Hola, mu usuario es carloscruz_205, gracias
