### ISSUE TITLE
Generar carpeta dropbox para albergar insumos para desarrollo modelo vulnerabilidad socio-institucional #PAPIIT

### ISSUE THREAD

**Issue by yosunemiquela** [lancis-apc/espejos-lancis#44]
De favor generar una carpeta para albergar todos los insumos para el desarrollo el modelo de vulnerabilidad costera para el grupo socio-institucional

**Comment by edithvilla** [comment]
@yosunemiquela está creada la carpetas "insumos" en:

\PAPIIT\pap_socio_intitucional\insumos

también dentro de esta carpeta se crearon las subcarpetas: "bd" que corresponde a las bases de datos y "sig" que es un respaldo de las capas originales que se van a utilizar
